// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjwpqmxxvixmqmkdvctu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqd3BxbXh4dml4bXFta2R2Y3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTc5ODIsImV4cCI6MjA2MjA5Mzk4Mn0.fr6DIuDp4ZTYSK8A7zRNq7zWdg36UzPY-BN45ANT-aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);